# Generated by Django 5.1.3 on 2024-11-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_Nova', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca_producto', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='productos/')), 
                ('categoria', models.CharField(choices=[('procesador', 'Procesador'), ('tarjeta_grafica', 'Tarjeta Gráfica'), ('memoria_ram', 'Memoria RAM'), ('almacenamiento', 'Almacenamiento'), ('placamadre', 'Placa Madre'), ('fuentepoder', 'Fuente de poder'), ('pantalla', 'Pantalla')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Almacenamiento',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_Nova.producto')),
                ('capacidad_almacenamiento', models.CharField(choices=[('Null', 'Sin especificar'), ('16GB', '16GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('500GB', '500GB'), ('1TB', '1TB'), ('2TB', '2TB')], default='null', max_length=50)),
                ('tipo_almacenamiento', models.CharField(choices=[('Null', 'Sin especificar'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('M2NVMe', 'M.2NVMe')], default='Null', max_length=50)),
            ],
            bases=('web_Nova.producto',),
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_Nova.producto')),
                ('potencia', models.CharField(choices=[('Null', 'Sin especificar'), ('500W', '500 Watts'), ('550W', '550 Watts'), ('600W', '600 Watts'), ('700W', '700 Watts'), ('800W', '800 Watts'), ('1000W', '1000 Watts')], default='Null', max_length=50)),
                ('certificacion', models.CharField(choices=[('Null', 'Sin especificar'), ('white', '80 PLUS White'), ('silver', '80 PLUS Silver'), ('gold', '80 PLUS Gold'), ('platinum', '80 PLUS Platinum'), ('titanium', '80 PLUS Titanium')], default='Null', max_length=50)),
                ('modularidad', models.CharField(choices=[('Null', 'Sin especificar'), ('modular', 'Modular'), ('no_modular', 'No Modular'), ('semi_modular', 'Semi-Modular')], default='Null', max_length=50)),
            ],
            bases=('web_Nova.producto',),
        ),
        migrations.CreateModel(
            name='MemoriaRAM',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_Nova.producto')),
                ('capacidad_ram', models.PositiveIntegerField()),
                ('tipo_memoria', models.CharField(choices=[('Null', 'Sin especificar'), ('DRR4', 'DRR4'), ('DRR5', 'DRR5')], default='null', max_length=50)),
            ],
            bases=('web_Nova.producto',),
        ),
        migrations.CreateModel(
            name='Pantalla',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_Nova.producto')),
                ('tamaño_pantalla', models.CharField(choices=[('Null', 'Sin especificar'), ('24', '24 Pulgadas'), ('27', '27 Pulgadas'), ('32', '32 Pulgadas'), ('38', '38 Pulgadas')], default='Null', max_length=50)),
                ('resolucion', models.CharField(choices=[('Null', 'Sin especificar'), ('1920x1080', '1920x1080'), ('2560x1080', '2560x1080')], default='Null', max_length=50)),
                ('frecuencia', models.CharField(choices=[('Null', 'Sin especificar'), ('60Hz', '60Hz'), ('120Hz', '120Hz'), ('144Hz', '144Hz'), ('160Hz', '160Hz'), ('200Hz', '200Hz'), ('240Hz', '240Hz'), ('260Hz', '260Hz')], default='Null', max_length=50)),
                ('tipo_panel', models.CharField(choices=[('Null', 'Sin especificar'), ('IPS', 'IPS'), ('VA', 'VA'), ('TN', 'TN')], default='Null', max_length=50)),
            ],
            bases=('web_Nova.producto',),
        ),
        migrations.CreateModel(
            name='PlacaMadre',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_Nova.producto')),
                ('socket', models.CharField(choices=[('Null', 'Sin especificar'), ('AM4', 'AM4'), ('AM5', 'AM5'), ('Inter', 'Intel')], default='Null', max_length=50)),
                ('tipo_memoria', models.CharField(choices=[('Null', 'Sin especificar'), ('DRR4', 'DRR4'), ('DRR5', 'DRR5')], default='Null', max_length=50)),
            ],
            bases=('web_Nova.producto',),
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_Nova.producto')),
                ('nucleos', models.PositiveIntegerField()),
                ('frecuencia_base', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('web_Nova.producto',),
        ),
        migrations.CreateModel(
            name='TarjetaGrafica',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_Nova.producto')),
                ('memoria_grafica', models.CharField(choices=[('Null', 'Sin especificar'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('14GB', '14GB'), ('16GB', '16GB'), ('20GB', '20GB'), ('24GB', '24GB')], default='null', max_length=50)),
            ],
            bases=('web_Nova.producto',),
        ),
    ]
