# Generated by Django 5.1.4 on 2024-12-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_Nova', '0005_alter_producto_precio_producto_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
